### Sending a small request
POST http://localhost:7071/api/script HTTP/1.1
content-type: application/json

< ./example-small.json

### Sending a large request
POST http://localhost:7071/api/script HTTP/1.1
content-type: application/json

< ./example-large.json
